name: Java CI with Maven

on:
  push:
    branches: [ "main", "develop" ]
  pull_request:
    branches: [ "main", "develop" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout do código
      uses: actions/checkout@v4

    - name: Configurar Java
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '21'
        cache: 'maven'

    - name: Build + Testes + Coverage
      run: mvn -B clean verify

    - name: SonarCloud Scan
      run: mvn -B sonar:sonar \
        -Dsonar.projectKey=andersonsmachadoinfnet_25E4_5-PB-EngenhariaDisciplinadaDeSoftwares-TP4 \
        -Dsonar.organization=andersonsmachadoinfnet \
        -Dsonar.host.url=https://sonarcloud.io \
        -Dsonar.login=${{ secrets.SONAR_TOKEN }}

    - name: Upload dos relatórios de teste
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: test-results
        path: target/surefire-reports/

    - name: Upload cobertura (JaCoCo)
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: coverage-report
        path: target/site/jacoco/